# Generated by Django 4.2.6 on 2024-05-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0003_user_activity_user_age_user_gender_user_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
