# Generated by Django 4.2.6 on 2024-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0005_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='name',
            new_name='FoodName',
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
