# Generated by Django 4.2.6 on 2024-05-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0006_rename_name_foods_foodname_alter_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='Protien',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='calories',
        ),
        migrations.AddField(
            model_name='foods',
            name='LinkDrive',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='foods',
            name='Protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foods',
            name='TheDescription',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='foods',
            name='YoutubeLink',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='foods',
            name='Fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foods',
            name='Calories',
            field=models.FloatField(default=0),
        ),
    ]
