# Generated by Django 4.2.6 on 2024-05-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0007_remove_foods_protien_remove_foods_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='Carbs',
            field=models.FloatField(default=0),
        ),
    ]
