# Generated by Django 4.2.6 on 2024-05-31 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0012_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
