# Generated by Django 4.2.6 on 2024-05-31 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0015_user_ideal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ideal_weight',
        ),
    ]
