# Generated by Django 4.2.6 on 2024-06-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0016_remove_user_height_remove_user_ideal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='likes',
        ),
    ]
