# Generated by Django 4.2.6 on 2024-06-02 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0017_remove_foods_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
