# Generated by Django 4.2.6 on 2024-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0019_user_height_user_ideal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='LinkDrive',
            field=models.CharField(default='Images/bagel.jpg', max_length=500),
        ),
    ]
