# Generated by Django 4.2.6 on 2024-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0020_alter_foods_linkdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='FoodName',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
