# Generated by Django 4.2.6 on 2024-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0022_alter_foods_foodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
