# Generated by Django 4.2.6 on 2024-06-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0023_user_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='LinkDrive',
            field=models.ImageField(default='foods_images/bagel.jpg', upload_to='foods_images/'),
        ),
    ]
