# Generated by Django 4.2.6 on 2024-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0025_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(blank=True, default='...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='calories',
            field=models.FloatField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ideal_weight',
            field=models.FloatField(blank=True, default='...', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, default='...', null=True),
        ),
    ]
